on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  test_scan:
    permissions:
      contents: read # to checkout repository code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: APISec|SCAN Testing
        uses: apisec-university/free-API-security-test-action@beta
        with:
          base_url: "https://abbeylincon.com"
          # specification_path: "<your-openapi-specification-file-goes-here>"
          apisecu_token: "U2FsdGVkX18VyYCLrUuQ9KOtwaSTwOfCF1NVieZIT3ktTJZCNTKNpEeMKgkZhwFs"
