# # This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# # For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # build:
  test_scan:
    permissions:
      contents:

    runs-on: ubuntu-latest

    strategy:
      # matrix:
        # node-version: [14.x, 16.x, 18.x]
        # # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    jobs:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: APISec|SCAN Testing
        uses: apisec-university/free-API-security-test-action@beta
        with:
          base_url: "https://abbeylincon.com"
          # specification_path: "<your-openapi-specification-file-goes-here>"
          apisecu_token: "U2FsdGVkX18VyYCLrUuQ9KOtwaSTwOfCF1NVieZIT3ktTJZCNTKNpEeMKgkZhwFs"
    # - uses: actions/checkout@v4
    # - name: Use Node.js ${{ matrix.node-version }}
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: ${{ matrix.node-version }}
    #     cache: 'npm'
    # - run: npm ci
    # - run: npm run build --if-present
    # - run: npm test
